config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms do
    resources :messages
  end
  root 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get "users", to: "devise/sessions#new"
  end
  get 'user/:id', to: 'users#show', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  scope :public_room, -> { where(private_room: false) }
  validates_uniqueness_of :name
  after_create_commit { broadcast_append_to 'chatrooms' }
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
  after_create_commit { broadcast_append_to chatroom }
  has_many_attached :attachments, dependent: :destroy


  def chatroom_file(index)
    file = attachments[index]
    if file.video? or file.image?
      file.variant(resize_to_limit: [150,150]).processed
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login
  validate :validate_username
  scope :all_excluding_current_user, -> (user) {where.not(id: user)}
  after_create_commit { broadcast_append_to 'users' }
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
   # updates user list without updating page through Redis and Hotwire
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def login
  @login || self.username || self.email
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # include Turbo::StreamsHelper
  # include Turbo::FramesHelper
  

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  
  def index
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.public_room
    @users = User.all_excluding_current_user(current_user)
    # exclude current user
    render 'index'
  end

  def show
    @singular_chatroom = Chatroom.find(params[:id])
    @message = Message.new
    @messages = @singular_chatroom.messages.order(created_at: :asc)
   
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.public_room
    @users = User.all_excluding_current_user(current_user)
    render 'index'

  end

  def create
    @chatroom = Chatroom.create(name: params['chatroom']['name'])
  end


  # def create
  #   @chatroom = Chatroom.new(chatroom_params)
  #   @chatroom.save
  # end


  # private

  # def chatroom_params
  #   params.require(:chatroom).permit(:name)
  # end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = current_user.messages.create(body: params_message[:body], chatroom_id: params[:chatroom_id], attachments: params_message[:attachments])
  end

  private

  def params_message
    params.require(:message).permit(:body, attachments: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/emojihelper.rb
module EmojiHelper
  def emojify(content)
    h(content).to_str.gsub(/:([\w+-]+):/) do |match|
      if emoji = Emoji.find_by_alias($1)
        %(<img alt="#$1" src="#{image_path("emoji/#{emoji.image_filename}")}" style="vertical-align:middle" width="20" height="20" />)
      else
        match
      end
    end.html_safe if content.present?
  end
end

eye_emoji = Emoji.find_by_alias "eyes"

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chatrooms/_chatroom.html.erb
<div>

  <div class="card no-outline mb-2 room-card">
  <h4><%= link_to chatroom.name.capitalize, chatroom, class:"text-info" %></h4>
  </div>

</div>

app/views/chatrooms/index.html.erb
<div id="chatroom_container" class="row blk_background text-light">

  <div id="side_panel" class="col-md-4 col-sm-4">
  <h4> Welcome to Hathi! 𓃰 </h4>
  </br>
  <h5> Hello <%= current_user.username.capitalize%> &nbsp (｡◕‿◕｡) </h5> </br></br>
  <h5> Online Users: </h5>
  <%= turbo_stream_from "users" %>
  <%# <% if @users.onlinestatus?%> 
    <div id = "users">
    <%= render @users%>
    </div></br> 
  <%# <%end%>
  <h5> Chat Rooms </h5>
  <%= turbo_stream_from "chatrooms" %>
    <div id = "chatrooms">
    <%= render @chatrooms %>
    </div>
  <%= render 'layouts/new_chatroom_form' %>
    <div class="text-info ">
    Total Members:  <%= @users.uniq.count + 1%> 
    </div>
  </div>


  <div id="room_container"
  class="col-md-8 col-sm-8 bg-dark text-light">
  <% if @singular_chatroom %>
    <div id="single_room">
    <h3 class="text-center"> <%=  @singular_chatroom.name.capitalize %> </h3>
    <%= turbo_stream_from @singular_chatroom %>
    <div id="messages">
    <%= render @messages %>
    </div>

  <%= render 'layouts/new_message_form' %>
  </div>
    <% end %>
  </div>
</div>

app/views/layouts/_new_chatroom_form.html.erb
<%= form_with(model: @chatroom, remote: true,format: :turbo_stream, class:'d-flex') do |f| %>
  <%= f.text_field :name, autocomplete: 'off',class: 'form-control', placeholder: 'ʕ•ᴥ•ʔ' %>
  <%= f.submit "Add Room", data: {disable_with: false}, class: 'btn btn-primary' %>
<% end %>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@singular_chatroom, @message], remote: true, class:'d-flex') do |f| %>
    <div >
      <label for="message_attachments">
        <i ></i>
      </label>
      <%= f.file_field(:attachments, multiple: true) %>
    </div>
    <%= f.text_field  :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off', placeholder: '𓃰𓃰𓃰𓃰𓃰𓃰' %>
    <%= f.submit "Send Message", data: {disable_with: false}, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hathi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_include_tags %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <style>
      <%= ".message-#{current_user&.id}" %> {
      background-color: #8907ed !important;
      padding: 12px;
      }
      <%= ".ttp-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end;
      }
    </style>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="ttp-<%=message.user.id%>">

  <div class="message-box message-<%= message.user.id %>">
  <div>
    <small > <%= message.user.username.capitalize %> </small></br>
     <h4> <%= message.body %> </h4>
      <div id="time">
     </div>
      </div>
<% if message.attachments.attached? %>
      <% message.attachments.each_with_index do |attachment, index| %>
        <% if attachment.image? %>
          <%= image_tag(message.chatroom_file(index)) %>
        <% elsif attachment.video? %>
          <%= video_tag(url_for(attachment), controls:'') %>
        <% elsif attachment.audio? %>
          <%= audio_tag(url_for(attachment), controls: '') %>
        <% else %>
          <%= link_to attachment.filename, url_for(attachment) %>
        <% end %>
      <% end %>
    <% end %>
    </br>
<small> <%= time_ago_in_words(message.created_at) %> ago </small>

  </div>
</div>

app/views/pages/home.html.erb
<div id="chatroom_container" class = "blk_background text-light">
  <h1 >Welcome to Hathi </h1>
  <p>The next biggest social platform</p>

  <% if current_user%>

    <%=link_to 'Chat Rooms', chatrooms_path %>
    </br>
    <%=link_to 'Logout', destroy_user_session_path, method: :delete%>


  <%else%>

    <%=link_to 'Sign In', new_user_session_path, class: "btn btn-primary home_btn"%>
    </br></br>
    <%=link_to 'Sign Up', new_user_registration_path, class: "btn btn-primary home_btn"%>


  <%end%>


</div>

app/views/users/_user.html.erb
<div>
    <%=  user.username.capitalize%> </br>
    PeaNuts Score:
    <%= user.nuts %> </br></br></br>
</div>